name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Lint code
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Verify data.csv exists
        run: |
          ls -l data.csv || echo "data.csv is missing"
      - name: Run tests
        run: pytest
      - name: Debug: Check for model.pkl
        run: ls -l model.pkl || echo "model.pkl not found"
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Download Model Artifact
        uses: actions/download-artifact@v3
        with:
          name: model
      - name: Deploy Model
        run: |
          echo "Deploying model artifact"
          mkdir -p artifacts
          cp model.pkl artifacts/
      - name: Upload Deployed Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: artifacts/model.pkl
